SIMULATOR_: true

robot_config:

    joint_names:
      - robot_arm_joint1
      - robot_arm_joint2
      - robot_arm_joint3
      - robot_arm_joint4
      - robot_arm_joint5
      - robot_arm_joint6
      - robot_arm_joint7
    

    neutral_pose:
        robot_arm_joint1: -0.017792060227770554 
        robot_arm_joint2: -0.7601235411041661  
        robot_arm_joint3: 0.019782607023391807 
        robot_arm_joint4: -2.342050140544315 
        robot_arm_joint5: 0.029840531355804868 
        robot_arm_joint6: 1.5411935298621688 
        robot_arm_joint7: 0.7534486589746342
        
    joint_config:
        joint_acceleration_limit:
            robot_arm_joint1: 15.0 # rad / sec^2
            robot_arm_joint2: 7.5  # rad / sec^2
            robot_arm_joint3: 10.0 # rad / sec^2
            robot_arm_joint4: 12.5 # rad / sec^2
            robot_arm_joint5: 15.0 # rad / sec^2
            robot_arm_joint6: 20.0 # rad / sec^2
            robot_arm_joint7: 20.0 # rad / sec^2
            # robot_arm_finger_joint1: 12.0 # rad / sec^2
            # robot_arm_finger_joint2: 12.0 # rad / sec^2

        joint_velocity_limit:
            robot_arm_joint1: 2.1750 # rad / sec
            robot_arm_joint2: 2.1750 # rad / sec
            robot_arm_joint3: 2.1750 # rad / sec
            robot_arm_joint4: 2.1750 # rad / sec
            robot_arm_joint5: 2.6100 # rad / sec
            robot_arm_joint6: 2.6100 # rad / sec
            robot_arm_joint7: 2.6100 # rad / sec
            # robot_arm_finger_joint1: 2.0 # rad / sec
            # robot_arm_finger_joint2: 2.0 # rad / sec

        joint_position_limit:
            lower: 
                robot_arm_joint1: -2.8973 # rad
                robot_arm_joint2: -1.7628 # rad
                robot_arm_joint3: -2.8973 # rad
                robot_arm_joint4: -3.0718 # rad
                robot_arm_joint5: -2.8973 # rad
                robot_arm_joint6: -0.0175 # rad
                robot_arm_joint7: -2.8973 # rad
            upper:
                robot_arm_joint1: 2.8973 # rad
                robot_arm_joint2: 1.7628 # rad
                robot_arm_joint3: 2.8973 # rad
                robot_arm_joint4: -0.0698 # rad
                robot_arm_joint5: 2.8973 # rad
                robot_arm_joint6: 3.7525 # rad
                robot_arm_joint7: 2.8973 # rad

        joint_effort_limit:
            robot_arm_joint1: 87 # Nm
            robot_arm_joint2: 87 # Nm
            robot_arm_joint3: 87 # Nm
            robot_arm_joint4: 87 # Nm
            robot_arm_joint5: 12 # Nm
            robot_arm_joint6: 12 # Nm
            robot_arm_joint7: 12 # Nm            

gripper_config:
  joint_names:
    - robot_arm_finger_joint1
    - robot_arm_finger_joint2
  default_speed: 0.1  # [m/s]
  default_grasp_epsilon:
    inner: 0.005 # [m]
    outer: 0.005 # [m]
 
