controller_list:
  - name: fake_panda_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - robot_arm_joint1
      - robot_arm_joint2
      - robot_arm_joint3
      - robot_arm_joint4
      - robot_arm_joint5
      - robot_arm_joint6
      - robot_arm_joint7
  - name: fake_panda_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - robot_arm_finger_joint1
      - robot_arm_finger_joint2
initial:  # Define initial robot poses.
  - group: panda_arm
    pose: home
  - group: panda_gripper
    pose: gripper_open