
panda_gripper_controller:
  type: effort_controllers/JointGroupPositionController
  joints:
      - robot_arm_finger_joint1
      - robot_arm_finger_joint2
  robot_arm_finger_joint1:
    pid: {p: 5000,  i: 50, d: 0.5}
  robot_arm_finger_joint2:
    pid: {p: 5000,  i: 50, d: 0.5}
