gazebo_panda:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100


  effort_joint_position_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - robot_arm_joint1
      - robot_arm_joint2
      - robot_arm_joint3
      - robot_arm_joint4
      - robot_arm_joint5
      - robot_arm_joint6
      - robot_arm_joint7
    panda_joint1:
      pid: {p: 3000,  i: 10.0, d: 25.0}
    panda_joint2:
      pid: {p: 3000,  i: 10.0, d: 25.0}
    panda_joint3:
      pid: {p: 3000,  i: 10.0, d: 25.0}
    panda_joint4:
      pid: {p: 3000,  i: 10.0, d: 25.0}
    panda_joint5:
      pid: {p: 3000,  i: 10.0, d: 25.0}
    panda_joint6:
      pid: {p: 3000,  i: 10.0, d: 25.0}
    panda_joint7:
      pid: {p: 3000,  i: 10.0, d: 25.0}

  effort_joint_torque_controller:
    type: effort_controllers/JointGroupEffortController
    joints:
      - robot_arm_joint1
      - robot_arm_joint2
      - robot_arm_joint3
      - robot_arm_joint4
      - robot_arm_joint5
      - robot_arm_joint6
      - robot_arm_joint7

  # joint1_velocity_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: robot_arm_joint1
  #   pid: {p: 10,  i: 0.0, d: 0.1}
  # joint2_velocity_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: robot_arm_joint2
  #   pid: {p: 100,  i: 1.0, d: 0.1}
  # joint3_velocity_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: robot_arm_joint3
  #   pid: {p: 0.05,  i: 0.0, d: 0.01}
  # joint4_velocity_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: robot_arm_joint4
  #   pid: {p: 0.5,  i: 0.01, d: 0.1}
  # joint5_velocity_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: robot_arm_joint5
  #   pid: {p: 1.0,  i: 0.0, d: 0.01}
  # joint6_velocity_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: robot_arm_joint6
  #   pid: {p: 0.05,  i: 0.0, d: 0.01}
  # joint7_velocity_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: robot_arm_joint7
  #   pid: {p: 0.05,  i: 0.0, d: 0.01}


  # velocity_joint_velocity_controller: # group velocity control does not seem to be possible without velocity interface. Alternatively velocity control can be done independently for each joint using effort_controllers/JointVelocityController
  #   type: velocity_controllers/JointGroupVelocityController
  #   joints:
  #     - robot_arm_joint1
  #     - robot_arm_joint2
  #     - robot_arm_joint3
  #     - robot_arm_joint4
  #     - robot_arm_joint5
  #     - robot_arm_joint6
  #     - robot_arm_joint7
  #   robot_arm_joint1:
  #     pid: {p: 10,  i: 0.0, d: 0.1}
  #   robot_arm_joint2:
  #     pid: {p: 100,  i: 1.0, d: 0.1}
  #   robot_arm_joint3:
  #     pid: {p: 0.05,  i: 0.0, d: 0.01}
  #   robot_arm_joint4:
  #     pid: {p: 0.5,  i: 0.01, d: 0.1}
  #   robot_arm_joint5:
  #     pid: {p: 1.0,  i: 0.0, d: 0.01}
  #   robot_arm_joint6:
  #     pid: {p: 0.05,  i: 0.0, d: 0.01}
  #   robot_arm_joint7:
  #     pid: {p: 0.05,  i: 0.0, d: 0.01}
